apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx-app
spec:
  destination:
    name: ''
    namespace: helm-nginx-ns
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-nginx
    repoURL: 'https://github.com/dewandemo/argocd-example-apps'
    targetRevision: HEAD
    kustomize:
      namePrefix: devops-india-
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true